packages=(
  com.github.tchx84.Flatseal
  app.zen_browser.zen
  com.google.Chrome
  com.mattjakeman.ExtensionManager
  com.nextcloud.desktopclient.nextcloud
  com.spotify.Client
  com.unicornsonlsd.finamp
  io.github.kolunmi.Bazaar
  io.github.vikdevelop.SaveDesktop
  io.missioncenter.MissionCenter
  it.mijorus.gearlever
  net.davidotek.pupgui2
  io.github.flattool.Warehouse
  org.kde.kdenlive
  com.rustdesk.RustDesk
  io.github.giantpinkrobots.flatsweep
  org.gnome.eog
  io.github.realmazharhussain.GdmSettings
  md.obsidian.Obsidian
  com.github.wwmm.easyeffects
  com.parsecgaming.parsec
  org.equicord.equibop
  org.pulseaudio.pavucontrol
  org.onlyoffice.desktopeditors
  com.ranfdev.DistroShelf
)

flatpak install flathub "${packages[@]}"
