[Icon Theme]
Name=Adwaitaru-red
Comment=Gnome's Adwaita meets Ubuntu's Yaru - red accent color
Example=folder
Inherits=Adwaitaru,Adwaita,gnome,hicolor

# KDE Specific Stuff
DisplayDepth=32
LinkOverlay=link_overlay
LockOverlay=lock_overlay
ZipOverlay=zip_overlay
DesktopDefault=48
DesktopSizes=16,22,32,48,64,72,96,128
ToolbarDefault=22
ToolbarSizes=16,22,32,48
MainToolbarDefault=22
MainToolbarSizes=16,22,32,48
SmallDefault=16
SmallSizes=16
PanelDefault=32
PanelSizes=16,22,32,48,64,72,96,128

# Directory list
Directories=16x16/apps,16x16/devices,16x16/mimetypes,16x16/places,16x16/status,scalable/apps,scalable/categories,scalable/devices,scalable/mimetypes,scalable/places,scalable/status,symbolic/devices

[16x16/apps]
Context=Applications
Size=16
Type=Scalable

[16x16/devices]
Context=Devices
Size=16
Type=Scalable

[16x16/mimetypes]
Context=MimeTypes
Size=16
Type=Scalable

[16x16/places]
Context=Places
Size=16
Type=Scalable

[16x16/status]
Context=Status
Size=16
Type=Scalable

[scalable/apps]
Context=Applications
Size=128
MinSize=8
MaxSize=512
Type=Scalable

[scalable/categories]
Context=Categories
Size=128
MinSize=8
MaxSize=512
Type=Scalable

[scalable/devices]
Context=Devices
Size=128
MinSize=8
MaxSize=512
Type=Scalable

[scalable/mimetypes]
Context=MimeTypes
Size=128
MinSize=8
MaxSize=512
Type=Scalable

[scalable/places]
Context=Places
Size=128
MinSize=8
MaxSize=512
Type=Scalable

[scalable/status]
Context=Status
Size=128
MinSize=8
MaxSize=512
Type=Scalable

[symbolic/devices]
Context=Devices
Size=16
MinSize=8
MaxSize=512
Type=Scalable
