[Patch]

[Setting]
prefs_path             = /home/raul/.var/app/com.spotify.Client/config/spotify/prefs
current_theme          = marketplace
color_scheme           = 
replace_colors         = 1
overwrite_assets       = 0
spotify_launch_flags   = 
check_spicetify_update = 1
spotify_path           = /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/
inject_theme_js        = 1
inject_css             = 1
always_enable_devtools = 0

[Preprocesses]
disable_sentry     = 1
disable_ui_logging = 1
remove_rtl_rule    = 1
expose_apis        = 1

[AdditionalOptions]
experimental_features = 1
extensions            = fullAppDisplay.js
custom_apps           = marketplace|reddit|lyrics-plus
sidebar_config        = 0
home_config           = 1

; DO NOT CHANGE!
[Backup]
version = 1.2.84.475.ga1a748ff
with    = 2.43.1
