# Tradução do tema oh-my-posh (Catppuccin Mocha) pra Starship

format = """
$username\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$fill\
$golang\
$bun\
$rust\
$os\
$shell
$character"""

add_newline = false

[fill]
symbol = " "

[username]
style_user = "fg:#f9e2af"
style_root = "fg:#f9e2af"
format = "[ $user ]($style)"
show_always = true

[directory]
style = "fg:#89dceb"
format = "[ $path ]($style)"
truncation_length = 0
truncate_to_repo = false

[git_branch]
style = "fg:#b4befe"
format = "[ $symbol$branch]($style)"
symbol = ""

[git_status]
style = "fg:#eba0ac"
format = '([ 󱖫 {$all_status$ahead_behind}]($style))'
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
staged = "+${count}"
modified = "!${count}"

[cmd_duration]
style = "fg:#a6adc8"
format = "[ $duration ]($style)"
min_time = 0

[golang]
style = "fg:#1e1e2e bg:#74c7ec"
format = "[  $version ]($style)"
detect_files = ["go.mod", "go.sum", "go.work", "main.go"]

[bun]
style = "fg:#1e1e2e bg:#fbf0df"
format = "[  $version ]($style)"

[rust]
style = "fg:#1e1e2e bg:#fab387"
format = "[   $version ]($style)"

[os]
style = "fg:#89b4fa"
format = "[ $symbol ]($style)"
disabled = false

[os.symbols]
Fedora = " "

[shell]
style = "fg:#f9e2af"
format = "[ $indicator]($style)"
disabled = false
zsh_indicator = "zsh"
bash_indicator = "bash"
fish_indicator = "fish"

[character]
success_symbol = "[❯](fg:#a6e3a1)"
error_symbol = "[❯](fg:#f38ba8)"
