[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]
formatter = { command = "prettier", args = ["--parser", "babel"] }
auto-format = true

[[language]]
name = "tsx"
language-servers = ["typescript-language-server"]
formatter = { command = "prettier", args = ["--parser", "babel-ts"] }
auto-format = true

[[language]]
name = "jsx"
language-servers = ["typescript-language-server"]
formatter = { command = "prettier", args = ["--parser", "babel"] }
auto-format = true

[[language]]
name = "go"
indent = { tab-width = 2, unit = "  " }
language-servers = ["gopls"]
formatter = { command = "goimports" }
auto-format = true

[[language]]
name = "rust"
indent = { tab-width = 2, unit = "  " }
language-servers = ["rust-analyzer"]
formatter = { command = "rustfmt", args = ["--edition", "2021"] }
auto-format = true

[[language]]
name = "python"
language-servers = ["pylsp"]
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[[language]]
name = "lua"
language-servers = ["lua-language-server"]
formatter = { command = "stylua", args = ["-"] }
auto-format = true

[[language]]
name = "toml"
language-servers = ["taplo"]
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true
